// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Tyrqvir/otus_hw/hw12_13_14_15_calendar/internal/broker"
	"github.com/Tyrqvir/otus_hw/hw12_13_14_15_calendar/internal/config"
	"github.com/Tyrqvir/otus_hw/hw12_13_14_15_calendar/internal/logger"
	"github.com/Tyrqvir/otus_hw/hw12_13_14_15_calendar/internal/sender"
)

// Injectors from wire.go:

func InitializeDIForSender(config2 *config.Config, logger2 logger.Logger, rmqConfig broker.RMQConfig) (*sender.Sender, error) {
	connection := broker.NewConnection(rmqConfig, logger2, config2)
	consumer := broker.NewConsumer(config2, logger2, connection)
	senderSender := sender.New(logger2, consumer, connection)
	return senderSender, nil
}
