// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Tyrqvir/otus_hw/hw12_13_14_15_calendar/internal/broker"
	"github.com/Tyrqvir/otus_hw/hw12_13_14_15_calendar/internal/config"
	"github.com/Tyrqvir/otus_hw/hw12_13_14_15_calendar/internal/logger"
	"github.com/Tyrqvir/otus_hw/hw12_13_14_15_calendar/internal/scheduler"
)

// Injectors from wire.go:

func InitializeDIForScheduler(config2 *config.Config, logger2 logger.ILogger) (*scheduler.Scheduler, error) {
	rabbitMQ := broker.New(config2, logger2)
	schedulerScheduler := scheduler.New(config2, logger2, rabbitMQ)
	return schedulerScheduler, nil
}
