version: '3.9'

services:
  calendar:
    build:
      context: ./..
      dockerfile: ./build/Dockerfile
      args:
        BIN_FILE: "/opt/calendar/calendar-app"
        APP_FOLDER: "calendar"
        CONFIG_FILE_EXTERNAL: "./configs/calendar_config.toml"
    restart: unless-stopped
    container_name: calendar
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${GRPS_PORT}:${GRPS_PORT}
    depends_on:
      - db

  db:
    image: postgres:${DB_VERSION}
    container_name: db
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d calendar" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./migrations/schema:/docker-entrypoint-initdb.d
