[logger]
level = "debug" # should be "info", "warn", "info", "error". See logger.go in logger package

[storage]
provider = "sql" # should be "sql", "in-memory"
DSN = "host=0.0.0.0 port=5432 user=postgres password=megapass dbname=calendar sslmode=disable"

[http]
host = "0.0.0.0"
port = "85"
write_timeout = "5s"
read_timeout = "5s"
read_header_timeout = "5s"

[grps]
port = "86"
