[logger]
level = "debug" # should be "info", "warn", "info", "error". See logger.go in logger package

[consumer]
tag = "simple-consumer"
connectionName = "sample-consumer"

[rmq]
dsn = "amqp://guest:guest@localhost:5672"
queue = "calendar"
exchangeName = "test-exchange"
exchangeType = "direct"
bindingKey = "test-key"
