[logger]
level = "debug" # should be "info", "warn", "info", "error". See logger.go in logger package

[consumer]
dsn = "amqp://guest:guest@0.0.0.0:5672"
queue = "calendar"
exchangeName = "test-exchange"
exchangeType = "direct"
bindingKey = "test-key"
